115 fetch my organizations
hamrolifebank/event-pwa pull request #118
Opened 2023-01-10 11:29 UTC by PitamberRana

2023-01-10 11:37 UTC, su-de-sh commented on src/redux/reducers/myJoinedOrgReducer.js
> +    console.log("reducer data", data);
remove console.log

2023-01-10 11:43 UTC, rushilshakya requested changes, later dismissed

2023-01-10 11:43 UTC, rushilshakya commented on src/redux/reducers/myJoinedOrgReducer.js
> +    console.log("reducer data", data);
remove console.log

2023-01-12 09:44 UTC, SurazGaire approved these changes

2023-01-12 10:07 UTC, SurazGaire approved these changes

2023-01-12 10:07 UTC, merged